using System.Collections;
using System.Collections.Generic;
using System.IO;
using System;
using SimpleJSON;

public enum FileType { Json}
public class Tracker
{
    // -------------------- VARIABLES -------------------- //
    private string TELEMETRY_PATH = "Assets/Telemetry/Results/";

    private static Tracker instance;

    private static Queue<TrackerEvent> _eventQueue;

    private JSONObject _jsonData;
    private string _fileName = "";

    // -------------------- FUNCIONES -------------------- //

    public static Tracker Instance
    {
        get
        {
            if (instance == null)
            {
                instance = new Tracker();
                _eventQueue = new Queue<TrackerEvent>();
                instance.InitJSONFile();
            }
            return instance;
        }
    }

    // Returns the amount of events in queue
    public int GetQueueNumEvents() { return _eventQueue.Count; }

    // Adds an event to the event queue
    public void AddEvent(TrackerEvent trackerEvent)
    {
        _eventQueue.Enqueue(trackerEvent);
    }

    // Dumps the set number of events to json 
    // If numEvents == -1, dumps all the events left in the queue
    public void DumpEventsToFile(int numEvents = -1, FileType fType = FileType.Json)
    {
        if(_eventQueue.Count > 0)
        {
            if (numEvents > 0)
            {
                for(int i=0; i<numEvents && _eventQueue.Count>0; i++)
                {
                    WriteToJson();
                }
            }
            else
            {
                while (_eventQueue.Count > 0)
                {
                    WriteToJson();
                }
                CloseJsonFile();
            }
        }
    }

    // If it has a fileName assigned, returns the file and will add data there
    // If it hasn't, finds the amount of files with the same date as filename
    // If none, assigns "date_1", if some "date_X" (each number refers to a play that day)
    // Saves all the data as Telemetry/Results/date/date_0.json
    private void InitJSONFile()
    {
        string auxFileName = System.DateTime.Now.ToShortDateString();
        auxFileName = auxFileName.Replace("/", "");
        
        string auxFilePath;
        int numPlaysToday;

        // if its the first time it tries to dump data in this play, tries to find the folder and the amount of previous files today
        if (_fileName == "")
        {
            TELEMETRY_PATH += (auxFileName + "/");
            // searches for the folder with all the data from previous plays today
            // if none found, creates empty folder
            if (Directory.Exists(TELEMETRY_PATH))
            {
                // counts only json files, not the autogenerated metas
                numPlaysToday = Directory.GetFiles(TELEMETRY_PATH, "*.json").Length;
            }
            else 
            {
                Directory.CreateDirectory(TELEMETRY_PATH);
                numPlaysToday = 0;
            }
            _fileName = auxFileName + "_" + numPlaysToday;
            auxFilePath = TELEMETRY_PATH + "/" + _fileName + ".json";
            File.WriteAllText(auxFilePath, "[\n");
        }     
    }
    private void WriteToJson()
    {
        JSONObject obj = new JSONObject();
        TrackerEvent auxTE = _eventQueue.Dequeue();
        auxTE.DumpEventDataToJson(ref obj);
        File.AppendAllText(TELEMETRY_PATH + _fileName + ".json", obj.ToString(4) + ",\n");
    }

    private void CloseJsonFile()
    {
        using (FileStream fs = new FileStream(TELEMETRY_PATH + _fileName + ".json", FileMode.Open))
        {
            fs.SetLength(fs.Length - 2);
            fs.Close();
        }

        File.AppendAllText(TELEMETRY_PATH + _fileName + ".json", "\n]");
    }
}
